import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Components based dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar/>
        <div className="flex justify-start items-start gap-5 mt-18 w-full flex-wrap-reverse sm:flex-nowrap"> 
          {/* Sidebar Wrapper */}
          <div className='w-full bottom-0 left-0 p-5 sm:static sm:w-auto xl:w-1/5 sm:h-165 -mt-5'>
            <Sidebar/>
          </div>
          
          {/* Main Content */}
          <div className='w-full sm:w-4/5 border border-slate-900 rounded-md sm:h-155 h-98 sm:mx-0 mx-5 p-5  overflow-auto'>
            <div className="flex-shrink-0">
              {children}
            </div>
          </div>
        </div>

      </body>
    </html>
  );
}
